CREATE TABLE IF NOT EXISTS M_USERS(USERID VARCHAR(20) PRIMARY KEY, PASSWORD VARCHAR(20) NOT NULL, FULLNAME NVARCHAR(200) NOT NULL, EMAIL VARCHAR(50) NULL DEFAULT NULL, MOBILE VARCHAR(20) NULL DEFAULT NULL, ROLE SMALLINT(1) NOT NULL , CREATEBY VARCHAR(20) NULL DEFAULT NULL, CREATEDATE DATETIME DEFAULT (DATETIME('NOW')));

CREATE TABLE IF NOT EXISTS M_CUSTOMERS(ID INTEGER PRIMARY KEY AUTOINCREMENT, COMPANYNAME NVARCHAR(200) NOT NULL, COMPANYADDRESS NVARCHAR(300) NOT NULL, COMPANYMOBILE VARCHAR(20) NOT NULL, CUSNAME VARCHAR(20) NOT NULL, CUSEMAIL VARCHAR(50) NULL DEFAULT NULL, CUSMOBILE VARCHAR(20) NULL DEFAULT NULL, USERID VARCHAR(20) NULL DEFAULT NULL, CREATEDATE DATETIME DEFAULT (DATETIME('NOW')));

CREATE TABLE IF NOT EXISTS M_DEVICES(ID INTEGER PRIMARY KEY AUTOINCREMENT, DEVICENAME nvarchar(300) NULL DEFAULT NULL, MACADDRESS VARCHAR(50) NULL DEFAULT NULL, USERID VARCHAR(20) NULL DEFAULT NULL, CREATEDATE DATETIME DEFAULT (DATETIME('NOW')));

CREATE TABLE IF NOT EXISTS CUSTOMERKEYS(CUSID INTEGER NOT NULL, KEYCODE VARCHAR(100) NOT NULL, USERID VARCHAR(20) NOT NULL, CREATEDATE DATETIME DEFAULT (DATETIME('NOW')));

CREATE TABLE IF NOT EXISTS KEYDEVICES(KEYCODE VARCHAR(100) NOT NULL, MACHINECODE VARCHAR(100) NOT NULL,  MACADDRESS VARCHAR(50) NULL DEFAULT NULL, USERID VARCHAR(20) NULL DEFAULT NULL, CREATEDATE DATETIME DEFAULT (DATETIME('NOW')));


INSERT INTO M_USERS (USERID, PASSWORD, FULLNAME, EMAIL, MOBILE, ROLE) VALUES ('admin', 'admin', 'NGUYỄN VĂN HIẾU', 'HIEU@AKB.COM.VN', '0968901256', 0);






