'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GiaPha.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property add_user() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("add_user", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AddChilds48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddChilds48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AKBlogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AKBlogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BgFemale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BgFemale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BgMale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BgMale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property binary_tree_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("binary_tree_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CloseBoxRed24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CloseBoxRed24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property couple64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("couple64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DBBackup16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBBackup16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DBBackup32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBBackup32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DBRestore16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBRestore16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exit16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exit32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FamilyInfo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FamilyInfo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property FamilyTree() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FamilyTree", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gender_man16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gender_man16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gender_unknown16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gender_unknown16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gender_woman16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gender_woman16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help_contents() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_contents", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Help16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HusbandWife16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HusbandWife16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property information() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("information", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property keys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property log_in22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log_in22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_icon100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_icon100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logout32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medal_gold_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medal_gold_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medal_gold_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medal_gold_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medal_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medal_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MemberAdd16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MemberAdd16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MemberAdd32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MemberAdd32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MemberInfo32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MemberInfo32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MemberSearch16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MemberSearch16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MemberSearch24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MemberSearch24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MemberSearch32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MemberSearch32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MSWord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MSWord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewImg_B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewImg_B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewImg_B_36_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewImg_B_36_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewImg_Fa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewImg_Fa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewImg_Fa_36_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewImg_Fa_36_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewImg_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewImg_G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewImg_G_36_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewImg_G_36_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewImg_Mo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewImg_Mo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewImg_Mo_36_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewImg_Mo_36_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_avatar_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_avatar_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_avatar_m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_avatar_m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noavatar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noavatar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property office_girl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("office_girl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property pass_change() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("pass_change", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property passchg128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("passchg128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdficon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdficon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PersionalInfo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PersionalInfo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pic_frame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic_frame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plus16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plus24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property printer24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property printer32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property setting32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setting32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_add2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_add2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Statistic16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Statistic16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm con nuôi.
        '''</summary>
        Friend ReadOnly Property StrAddAdoptChild() As String
            Get
                Return ResourceManager.GetString("StrAddAdoptChild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm cha nuôi.
        '''</summary>
        Friend ReadOnly Property StrAddAdoptFather() As String
            Get
                Return ResourceManager.GetString("StrAddAdoptFather", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm mẹ nuôi.
        '''</summary>
        Friend ReadOnly Property StrAddAdoptMother() As String
            Get
                Return ResourceManager.GetString("StrAddAdoptMother", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm anh.
        '''</summary>
        Friend ReadOnly Property StrAddBro() As String
            Get
                Return ResourceManager.GetString("StrAddBro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chọn anh/chị/em từ danh sách.
        '''</summary>
        Friend ReadOnly Property StrAddBroSisFromList() As String
            Get
                Return ResourceManager.GetString("StrAddBroSisFromList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm con.
        '''</summary>
        Friend ReadOnly Property StrAddChild() As String
            Get
                Return ResourceManager.GetString("StrAddChild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm con gái.
        '''</summary>
        Friend ReadOnly Property StrAddDaughter() As String
            Get
                Return ResourceManager.GetString("StrAddDaughter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đặt làm trưởng họ.
        '''</summary>
        Friend ReadOnly Property StrAddFamilyHead() As String
            Get
                Return ResourceManager.GetString("StrAddFamilyHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chọn cha mẹ từ danh sách.
        '''</summary>
        Friend ReadOnly Property StrAddFaMoFromList() As String
            Get
                Return ResourceManager.GetString("StrAddFaMoFromList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm cha.
        '''</summary>
        Friend ReadOnly Property StrAddFather() As String
            Get
                Return ResourceManager.GetString("StrAddFather", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm mới vợ/chồng.
        '''</summary>
        Friend ReadOnly Property StrAddHusWif() As String
            Get
                Return ResourceManager.GetString("StrAddHusWif", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm mới vợ/chồng từ danh sách.
        '''</summary>
        Friend ReadOnly Property StrAddHusWifFromList() As String
            Get
                Return ResourceManager.GetString("StrAddHusWifFromList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm con từ danh sách.
        '''</summary>
        Friend ReadOnly Property StrAddKidFromList() As String
            Get
                Return ResourceManager.GetString("StrAddKidFromList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm mẹ.
        '''</summary>
        Friend ReadOnly Property StrAddMother() As String
            Get
                Return ResourceManager.GetString("StrAddMother", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Đặt làm tổ phụ.
        '''</summary>
        Friend ReadOnly Property StrAddRoot() As String
            Get
                Return ResourceManager.GetString("StrAddRoot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm chị.
        '''</summary>
        Friend ReadOnly Property StrAddSis() As String
            Get
                Return ResourceManager.GetString("StrAddSis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm con trai.
        '''</summary>
        Friend ReadOnly Property StrAddSon() As String
            Get
                Return ResourceManager.GetString("StrAddSon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm em trai.
        '''</summary>
        Friend ReadOnly Property StrAddYoBro() As String
            Get
                Return ResourceManager.GetString("StrAddYoBro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm em gái.
        '''</summary>
        Friend ReadOnly Property StrAddYoSis() As String
            Get
                Return ResourceManager.GetString("StrAddYoSis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anh em.
        '''</summary>
        Friend ReadOnly Property StrBros() As String
            Get
                Return ResourceManager.GetString("StrBros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hủy quan hệ cha mẹ hiện tại.
        '''</summary>
        Friend ReadOnly Property StrDelFaMoRel() As String
            Get
                Return ResourceManager.GetString("StrDelFaMoRel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loại khỏi danh sách trưởng họ.
        '''</summary>
        Friend ReadOnly Property StrDelFromFamilyHead() As String
            Get
                Return ResourceManager.GetString("StrDelFromFamilyHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Không phải tổ phụ.
        '''</summary>
        Friend ReadOnly Property StrDelFromRoot() As String
            Get
                Return ResourceManager.GetString("StrDelFromRoot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hủy bỏ quan hệ vợ chồng.
        '''</summary>
        Friend ReadOnly Property StrDelHusWifRel() As String
            Get
                Return ResourceManager.GetString("StrDelHusWifRel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Xóa thông tin thành viên này.
        '''</summary>
        Friend ReadOnly Property StrDelMember() As String
            Get
                Return ResourceManager.GetString("StrDelMember", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cha mẹ.
        '''</summary>
        Friend ReadOnly Property StrFaMo() As String
            Get
                Return ResourceManager.GetString("StrFaMo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vợ chồng.
        '''</summary>
        Friend ReadOnly Property StrHusWif() As String
            Get
                Return ResourceManager.GetString("StrHusWif", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Con cái.
        '''</summary>
        Friend ReadOnly Property StrKids() As String
            Get
                Return ResourceManager.GetString("StrKids", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thêm mới thành viên.
        '''</summary>
        Friend ReadOnly Property StrNewMem() As String
            Get
                Return ResourceManager.GetString("StrNewMem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thông tin cá nhân.
        '''</summary>
        Friend ReadOnly Property StrPersonInfo() As String
            Get
                Return ResourceManager.GetString("StrPersonInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cập nhật lại thứ bậc.
        '''</summary>
        Friend ReadOnly Property StrRefreshGeneration() As String
            Get
                Return ResourceManager.GetString("StrRefreshGeneration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property task_done() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("task_done", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TreeS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TreeS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TreeS1Hoz32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TreeS1Hoz32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TreeS1Ver32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TreeS1Ver32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TreeS2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TreeS2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TreeView16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TreeView16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TreeView32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TreeView32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UnknownMember() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnknownMember", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_female_white_pink_brown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_female_white_pink_brown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_male_white_blue_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_male_white_blue_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property useradd64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("useradd64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UserInfo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UserInfo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UserInfo32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UserInfo32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
