'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property intGeneration() As Integer
            Get
                Return CType(Me("intGeneration"),Integer)
            End Get
            Set
                Me("intGeneration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property intCardSize() As Integer
            Get
                Return CType(Me("intCardSize"),Integer)
            End Get
            Set
                Me("intCardSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property intCardStyle() As Integer
            Get
                Return CType(Me("intCardStyle"),Integer)
            End Get
            Set
                Me("intCardStyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property intInitGeneration() As Integer
            Get
                Return CType(Me("intInitGeneration"),Integer)
            End Get
            Set
                Me("intInitGeneration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property intMaxDrawGeneration() As String
            Get
                Return CType(Me("intMaxDrawGeneration"),String)
            End Get
            Set
                Me("intMaxDrawGeneration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strCard1Bg() As String
            Get
                Return CType(Me("strCard1Bg"),String)
            End Get
            Set
                Me("strCard1Bg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strCreateMember() As String
            Get
                Return CType(Me("strCreateMember"),String)
            End Get
            Set
                Me("strCreateMember") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property intHozBuffer() As Integer
            Get
                Return CType(Me("intHozBuffer"),Integer)
            End Get
            Set
                Me("intHozBuffer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property intVerBuffer() As Integer
            Get
                Return CType(Me("intVerBuffer"),Integer)
            End Get
            Set
                Me("intVerBuffer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property blnShowUnknownBirthDay() As Boolean
            Get
                Return CType(Me("blnShowUnknownBirthDay"),Boolean)
            End Get
            Set
                Me("blnShowUnknownBirthDay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property intDeadDateShowType() As Integer
            Get
                Return CType(Me("intDeadDateShowType"),Integer)
            End Get
            Set
                Me("intDeadDateShowType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property blnTypeCardShort() As Boolean
            Get
                Return CType(Me("blnTypeCardShort"),Boolean)
            End Get
            Set
                Me("blnTypeCardShort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property intSelectedTypeCardShort() As Integer
            Get
                Return CType(Me("intSelectedTypeCardShort"),Integer)
            End Get
            Set
                Me("intSelectedTypeCardShort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yellow")>  _
        Public Property objColorBackgroupCard() As Global.System.Drawing.Color
            Get
                Return CType(Me("objColorBackgroupCard"),Global.System.Drawing.Color)
            End Get
            Set
                Me("objColorBackgroupCard") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("224, 224, 224")>  _
        Public Property objColorBackgroupCardDie() As Global.System.Drawing.Color
            Get
                Return CType(Me("objColorBackgroupCardDie"),Global.System.Drawing.Color)
            End Get
            Set
                Me("objColorBackgroupCardDie") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnShowBackgroupDie() As Boolean
            Get
                Return CType(Me("blnShowBackgroupDie"),Boolean)
            End Get
            Set
                Me("blnShowBackgroupDie") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property objColorText() As Global.System.Drawing.Color
            Get
                Return CType(Me("objColorText"),Global.System.Drawing.Color)
            End Get
            Set
                Me("objColorText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 8.25pt")>  _
        Public Property objFontDefaut() As Global.System.Drawing.Font
            Get
                Return CType(Me("objFontDefaut"),Global.System.Drawing.Font)
            End Get
            Set
                Me("objFontDefaut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property intSelectedTypeShowTree() As Integer
            Get
                Return CType(Me("intSelectedTypeShowTree"),Integer)
            End Get
            Set
                Me("intSelectedTypeShowTree") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("130")>  _
        Public Property intHozSize() As Integer
            Get
                Return CType(Me("intHozSize"),Integer)
            End Get
            Set
                Me("intHozSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("120")>  _
        Public Property intVerSize() As Integer
            Get
                Return CType(Me("intVerSize"),Integer)
            End Get
            Set
                Me("intVerSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnShowLevel() As Boolean
            Get
                Return CType(Me("blnShowLevel"),Boolean)
            End Get
            Set
                Me("blnShowLevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnShowGender() As Boolean
            Get
                Return CType(Me("blnShowGender"),Boolean)
            End Get
            Set
                Me("blnShowGender") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property intTypeDrawText() As Integer
            Get
                Return CType(Me("intTypeDrawText"),Integer)
            End Get
            Set
                Me("intTypeDrawText") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.GiaPha.My.MySettings
            Get
                Return Global.GiaPha.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
