'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("info_pass")>  _
        Public Property DB_USERPASSWORD() As String
            Get
                Return CType(Me("DB_USERPASSWORD"),String)
            End Get
            Set
                Me("DB_USERPASSWORD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ErrLog")>  _
        Public Property ERRLOG_FOLDER() As String
            Get
                Return CType(Me("ERRLOG_FOLDER"),String)
            End Get
            Set
                Me("ERRLOG_FOLDER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property MAIL_SMTP_PORT() As String
            Get
                Return CType(Me("MAIL_SMTP_PORT"),String)
            End Get
            Set
                Me("MAIL_SMTP_PORT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("akb_emctest@outlook.com.vn")>  _
        Public Property MAIL_POP_USER() As String
            Get
                Return CType(Me("MAIL_POP_USER"),String)
            End Get
            Set
                Me("MAIL_POP_USER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LogFolder")>  _
        Public Property LOG_FOLDER() As String
            Get
                Return CType(Me("LOG_FOLDER"),String)
            End Get
            Set
                Me("LOG_FOLDER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("outlook.office365.com")>  _
        Public Property MAIL_POP_HOST() As String
            Get
                Return CType(Me("MAIL_POP_HOST"),String)
            End Get
            Set
                Me("MAIL_POP_HOST") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property REG_USER_NO() As String
            Get
                Return CType(Me("REG_USER_NO"),String)
            End Get
            Set
                Me("REG_USER_NO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property QUERY_RETENTION_PERIOD() As String
            Get
                Return CType(Me("QUERY_RETENTION_PERIOD"),String)
            End Get
            Set
                Me("QUERY_RETENTION_PERIOD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.1.249\sqlexpress")>  _
        Public Property DB_HOSTNAME() As String
            Get
                Return CType(Me("DB_HOSTNAME"),String)
            End Get
            Set
                Me("DB_HOSTNAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("info_user")>  _
        Public Property DB_USERNAME() As String
            Get
                Return CType(Me("DB_USERNAME"),String)
            End Get
            Set
                Me("DB_USERNAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("995")>  _
        Public Property MAIL_POP_PORT() As String
            Get
                Return CType(Me("MAIL_POP_PORT"),String)
            End Get
            Set
                Me("MAIL_POP_PORT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WebLog")>  _
        Public Property WEB_LOG_FOLDER() As String
            Get
                Return CType(Me("WEB_LOG_FOLDER"),String)
            End Get
            Set
                Me("WEB_LOG_FOLDER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mail submit title jpb")>  _
        Public Property MAIL_SUBMIT_TITLE_JPN() As String
            Get
                Return CType(Me("MAIL_SUBMIT_TITLE_JPN"),String)
            End Get
            Set
                Me("MAIL_SUBMIT_TITLE_JPN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mail submit title eng")>  _
        Public Property MAIL_SUBMIT_TITLE_ENG() As String
            Get
                Return CType(Me("MAIL_SUBMIT_TITLE_ENG"),String)
            End Get
            Set
                Me("MAIL_SUBMIT_TITLE_ENG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mail_temp_jpn.txt")>  _
        Public Property MAIL_CONTENTS_JPN() As String
            Get
                Return CType(Me("MAIL_CONTENTS_JPN"),String)
            End Get
            Set
                Me("MAIL_CONTENTS_JPN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mail_temp_eng.txt")>  _
        Public Property MAIL_CONTENTS_ENG() As String
            Get
                Return CType(Me("MAIL_CONTENTS_ENG"),String)
            End Get
            Set
                Me("MAIL_CONTENTS_ENG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("info_db")>  _
        Public Property DB_DBNAME() As String
            Get
                Return CType(Me("DB_DBNAME"),String)
            End Get
            Set
                Me("DB_DBNAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property DEBUGFLG() As String
            Get
                Return CType(Me("DEBUGFLG"),String)
            End Get
            Set
                Me("DEBUGFLG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60000")>  _
        Public Property EXECUTION_CYCLE() As String
            Get
                Return CType(Me("EXECUTION_CYCLE"),String)
            End Get
            Set
                Me("EXECUTION_CYCLE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("huyennm@moli.vn")>  _
        Public Property FROM_MAILADDRESS() As String
            Get
                Return CType(Me("FROM_MAILADDRESS"),String)
            End Get
            Set
                Me("FROM_MAILADDRESS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.1.197")>  _
        Public Property MAIL_SMTP_HOST() As String
            Get
                Return CType(Me("MAIL_SMTP_HOST"),String)
            End Get
            Set
                Me("MAIL_SMTP_HOST") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("huyennm")>  _
        Public Property MAIL_SMTP_USER() As String
            Get
                Return CType(Me("MAIL_SMTP_USER"),String)
            End Get
            Set
                Me("MAIL_SMTP_USER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("huyennm")>  _
        Public Property MAIL_SMTP_PASS() As String
            Get
                Return CType(Me("MAIL_SMTP_PASS"),String)
            End Get
            Set
                Me("MAIL_SMTP_PASS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Emctest123456a@A")>  _
        Public Property MAIL_POP_PASS() As String
            Get
                Return CType(Me("MAIL_POP_PASS"),String)
            End Get
            Set
                Me("MAIL_POP_PASS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cuong@moli.vn")>  _
        Public Property MAIL_DESTINATION_ADMIN_ADDRESS() As String
            Get
                Return CType(Me("MAIL_DESTINATION_ADMIN_ADDRESS"),String)
            End Get
            Set
                Me("MAIL_DESTINATION_ADMIN_ADDRESS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property MAIL_SUBMIT_NUMBER() As String
            Get
                Return CType(Me("MAIL_SUBMIT_NUMBER"),String)
            End Get
            Set
                Me("MAIL_SUBMIT_NUMBER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\192.168.1.207\information_sharing")>  _
        Public Property SHARE_FOLDER() As String
            Get
                Return CType(Me("SHARE_FOLDER"),String)
            End Get
            Set
                Me("SHARE_FOLDER") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.EmcDataImport.My.MySettings
            Get
                Return Global.EmcDataImport.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
