 ---- テーブル作成 ---- 
 -- 業務名マスタ -- 
CREATE TABLE m_business_name
(
BUSINESS_NAME_NO			 INT NOT NULL
,BUSINESS_NAME_JPN			 VARCHAR(100) NOT NULL
,BUSINESS_NAME_ENG			 VARCHAR(100) NOT NULL
,PRIMARY KEY(BUSINESS_NAME_NO));

 -- 場所名マスタ -- 
CREATE TABLE m_place_name
(
PLACE_NAME_NO			 INT NOT NULL
,PLACE_NAME_JPN			 VARCHAR(100) NOT NULL
,PLACE_NAME_ENG			 VARCHAR(100) NOT NULL
,PLACE3_ID			 INT NOT NULL
,MAP_ID			 INT NOT NULL
,UP_DATE			 DATETIME NOT NULL
,PRIMARY KEY(PLACE_NAME_NO));

 -- 機関カテゴリマスタ -- 
CREATE TABLE m_inst_category
(
INST_CATEGORY_NO			 INT NOT NULL
,INST_CATEGORY_NAME_JPN			 VARCHAR(100) NOT NULL
,INST_CATEGORY_NAME_ENG			 VARCHAR(100) NOT NULL
,SORT_NO			 INT NOT NULL
,PRIMARY KEY(INST_CATEGORY_NO));

 -- 情報カテゴリマスタ -- 
CREATE TABLE m_info_category
(
INFO_CATEGORY_NO			 INT NOT NULL
,INFO_CATEGORY_NAME_JPN			 VARCHAR(100) NOT NULL
,INFO_CATEGORY_NAME_ENG			 VARCHAR(100) NOT NULL
,SORT_NO			 INT NOT NULL
,PRIMARY KEY(INFO_CATEGORY_NO));

 -- リンクカテゴリマスタ -- 
CREATE TABLE m_link_category
(
LINK_CATEGORY_NO			 INT NOT NULL
,LINK_CATEGORY_NAME_JPN			 VARCHAR(100) NOT NULL
,LINK_CATEGORY_NAME_ENG			 VARCHAR(100) NOT NULL
,SORT_NO			 INT NOT NULL
,PRIMARY KEY(LINK_CATEGORY_NO));

 -- グループマスタ -- 
CREATE TABLE m_group
(
GROUP_NO			 INT NOT NULL
,GROUP_NAME_JPN			 VARCHAR(100) NOT NULL
,GROUP_NAME_ENG			 VARCHAR(100) NOT NULL
,ADMIN_FLAG			 DECIMAL(1,0) NOT NULL
,SORT_NO			 INT NOT NULL
,PRIMARY KEY(GROUP_NO));

 -- 会社マスタ -- 
CREATE TABLE m_company
(
COMPANY_NO			 INT NOT NULL
,COMPANY_NAME_JPN			 VARCHAR(40) NOT NULL
,COMPANY_NAME_ENG			 VARCHAR(50) NOT NULL
,ABBREVIATIONS_JPN			 VARCHAR(40) NOT NULL
,ABBREVIATIONS_ENG			 VARCHAR(50) NOT NULL
,INST_CATEGORY_NO			 INT NOT NULL
,GROUP_NO			 INT NOT NULL
,DEL_FLAG			 DECIMAL(1,0)
,SORT_NO			 INT NOT NULL
,REG_USER_NO			 INT NOT NULL
,REG_DATE			 DATETIME NOT NULL
,UP_USER_NO			 INT
,UP_DATE			 DATETIME
,PRIMARY KEY(COMPANY_NO));

 -- ユーザマスタ -- 
CREATE TABLE m_user
(
USER_NO			 INT NOT NULL
,USER_ID			 VARCHAR(20) NOT NULL
,PASSWORD			 VARCHAR(30) NOT NULL
,PASSWORD_UP_DATE			 DATETIME NOT NULL
,EXPIRATION_DATE_S			 DATETIME NOT NULL
,EXPIRATION_DATE_E			 DATETIME NOT NULL
,LANGUAGE_TYPE			 DECIMAL(1,0) NOT NULL
,COMPANY_NO			 INT NOT NULL
,ORGANIZATION			 VARCHAR(100)
,USER_NAME			 VARCHAR(40)
,MAIL_ADDRESS			 VARCHAR(50) NOT NULL
,TEL			 VARCHAR(20)
,FAX			 VARCHAR(20)
,ZIP_CODE			 VARCHAR(8)
,ADDRESS			 VARCHAR(200)
,PERM_FLAG			 DECIMAL(1,0) NOT NULL
,JCMG_TAB_PERM			 DECIMAL(1,0)
,ANNOUNCE_REG_PERM			 DECIMAL(1,0)
,QUERY_REG_PERM			 DECIMAL(1,0)
,INCIDENT_CASE_REG_PERM			 DECIMAL(1,0)
,REQUEST_REG_PERM			 DECIMAL(1,0)
,INFORMATION_REG_PERM			 DECIMAL(1,0)
,MENU_PERM			 DECIMAL(1,0)
,ANNOUNCE_MAIL			 DECIMAL(1,0)
,BULLETIN_BOARD_MAIL			 DECIMAL(1,0)
,INCIDENT_CASE_MAIL			 DECIMAL(1,0)
,REQUEST_CONTENTS_MAIL			 DECIMAL(1,0)
,REMARKS			 VARCHAR(400)
,REG_USER_NO			 INT NOT NULL
,REG_DATE			 DATETIME NOT NULL
,UP_USER_NO			 INT
,UP_DATE			 DATETIME
,PRIMARY KEY(USER_NO));

 -- お知らせテーブル -- 
CREATE TABLE t_announce
(
ANNOUNCE_NO			 INT NOT NULL
,TITLE_JPN			 VARCHAR(8000)
,TITLE_ENG			 VARCHAR(8000)
,CONTENTS_JPN			 VARCHAR(8000)
,CONTENTS_ENG			 VARCHAR(8000)
,LANGUAGE_TYPE			 DECIMAL(1,0) NOT NULL
,CORRECTION_FLAG			 DECIMAL(1,0) NOT NULL
,FILE_NAME1			 VARCHAR(100)
,FILE_NAME2			 VARCHAR(100)
,FILE_NAME3			 VARCHAR(100)
,FILE_NAME4			 VARCHAR(100)
,FILE_NAME5			 VARCHAR(100)
,UNTRANSLATED			 DECIMAL(1,0) NOT NULL
,COMP_DATE			 DATETIME
,DATA_TYPE			 DECIMAL(1,0) NOT NULL
,REG_USER_NO			 INT NOT NULL
,REG_DATE			 DATETIME NOT NULL
,UP_USER_NO			 INT
,UP_DATE			 DATETIME
,PRIMARY KEY(ANNOUNCE_NO));

 -- 掲示板テーブル -- 
CREATE TABLE t_bulletin_board
(
BULLETIN_BOARD_NO			 INT NOT NULL
,INCIDENT_NO			 VARCHAR(100) NOT NULL
,OCCURRENCE_DATE			 DATETIME NOT NULL
,BUSINESS_NAME			 VARCHAR(100) NOT NULL
,PLACE3_ID			 INT NOT NULL
,INCIDENT_NAME_JPN			 VARCHAR(8000) NOT NULL
,INCIDENT_NAME_ENG			 VARCHAR(8000)
,CORRECTION_FLAG			 DECIMAL(1,0) NOT NULL
,UNTRANSLATED			 DECIMAL(1,0) NOT NULL
,COMP_DATE			 DATETIME
,REG_DATE			 DATETIME NOT NULL
,UP_USER_NO			 INT
,UP_DATE			 DATETIME
,PRIMARY KEY(BULLETIN_BOARD_NO));

 -- 問い合わせテーブル -- 
CREATE TABLE t_query
(
QUERY_NO			 INT NOT NULL
,QUERY_DATE			 DATETIME NOT NULL
,QUERY_USER_NO			 INT NOT NULL
,CONTENTS_JPN			 VARCHAR(8000)
,CONTENTS_ENG			 VARCHAR(8000)
,LANGUAGE_TYPE			 DECIMAL(1,0) NOT NULL
,CORRECTION_FLAG			 DECIMAL(1,0) NOT NULL
,PRIMARY KEY(QUERY_NO));

 -- JCMG事案テーブル -- 
CREATE TABLE t_incident_case
(
INCIDENT_CASE_NO			 INT NOT NULL
,S_DATE			 DATETIME NOT NULL
,TITLE_JPN			 VARCHAR(8000)
,TITLE_ENG			 VARCHAR(8000)
,CONTENTS_JPN			 VARCHAR(8000)
,CONTENTS_ENG			 VARCHAR(8000)
,LANGUAGE_TYPE			 DECIMAL(1,0) NOT NULL
,CORRECTION_FLAG			 DECIMAL(1,0) NOT NULL
,COMP_DATE			 DATETIME
,REG_USER_NO			 INT NOT NULL
,REG_DATE			 DATETIME NOT NULL
,UP_USER_NO			 INT
,UP_DATE			 DATETIME
,PRIMARY KEY(INCIDENT_CASE_NO));

 -- 依頼事項テーブル -- 
CREATE TABLE t_request
(
REQUEST_NO			 INT NOT NULL
,INCIDENT_CASE_NO			 INT NOT NULL
,TITLE_JPN			 VARCHAR(8000)
,TITLE_ENG			 VARCHAR(8000)
,CONTENTS_JPN			 VARCHAR(8000)
,CONTENTS_ENG			 VARCHAR(8000)
,LANGUAGE_TYPE			 DECIMAL(1,0) NOT NULL
,CORRECTION_FLAG			 DECIMAL(1,0) NOT NULL
,TMP_FILE_NAME1			 VARCHAR(100)
,TMP_FILE_NAME2			 VARCHAR(100)
,TMP_FILE_NAME3			 VARCHAR(100)
,TMP_FILE_NAME4			 VARCHAR(100)
,TMP_FILE_NAME5			 VARCHAR(100)
,PUBIC_FLAG1			 DECIMAL(1,0)
,PUBIC_FLAG2			 DECIMAL(1,0)
,PUBIC_FLAG3			 DECIMAL(1,0)
,PUBIC_FLAG4			 DECIMAL(1,0)
,PUBIC_FLAG5			 DECIMAL(1,0)
,REG_USER_NO			 INT NOT NULL
,REG_DATE			 DATETIME NOT NULL
,UP_USER_NO			 INT
,UP_DATE			 DATETIME
,PRIMARY KEY(REQUEST_NO));

 -- 情報テーブル -- 
CREATE TABLE t_information
(
INFORMATION_NO			 INT NOT NULL
,INCIDENT_CASE_NO			 INT NOT NULL
,TITLE_JPN			 VARCHAR(8000)
,TITLE_ENG			 VARCHAR(8000)
,CONTENTS_JPN			 VARCHAR(8000)
,CONTENTS_ENG			 VARCHAR(8000)
,LANGUAGE_TYPE			 DECIMAL(1,0) NOT NULL
,CORRECTION_FLAG			 DECIMAL(1,0) NOT NULL
,CONFIRM_DATE			 DATETIME
,CONTACT_INFO			 VARCHAR(13)
,COMPANY_NO			 INT
,INFO_CATEGORY_NO			 INT
,TMP_FILE_NAME1			 VARCHAR(100)
,TMP_FILE_NAME2			 VARCHAR(100)
,TMP_FILE_NAME3			 VARCHAR(100)
,TMP_FILE_NAME4			 VARCHAR(100)
,TMP_FILE_NAME5			 VARCHAR(100)
,PUBIC_FLAG1			 DECIMAL(1,0)
,PUBIC_FLAG2			 DECIMAL(1,0)
,PUBIC_FLAG3			 DECIMAL(1,0)
,PUBIC_FLAG4			 DECIMAL(1,0)
,PUBIC_FLAG5			 DECIMAL(1,0)
,REG_USER_NO			 INT NOT NULL
,REG_DATE			 DATETIME NOT NULL
,UP_USER_NO			 INT
,UP_DATE			 DATETIME
,PRIMARY KEY(INFORMATION_NO));

 -- リンク情報テーブル -- 
CREATE TABLE t_link
(
LINK_NO			 INT NOT NULL
,LINK_CATEGORY_NO			 INT
,LINK_NAME_JPN			 VARCHAR(1000) NOT NULL
,LINK_NAME_ENG			 VARCHAR(1000) NOT NULL
,URL			 VARCHAR(1000) NOT NULL
,BURNER_FILE_NAME1			 VARCHAR(100)
,SORT_NO			 INT NOT NULL
,REG_USER_NO			 INT NOT NULL
,REG_DATE			 DATETIME NOT NULL
,UP_USER_NO			 INT
,UP_DATE			 DATETIME
,PRIMARY KEY(LINK_NO));

 -- 機関_会社ソートテーブル -- 
CREATE TABLE t_inst_company_sort
(
USER_NO			 INT NOT NULL
,INST_CATEGORY_NO			 INT NOT NULL
,COMPANY_NO			 INT NOT NULL
,SORT_NO			 INT NOT NULL
);

 -- ログテーブル -- 
CREATE TABLE t_log
(
REG_DATE			 DATETIME NOT NULL
,LOGID			 INT NOT NULL
,CONTENT			 VARCHAR(8000) NOT NULL
);

 -- エラー拡張子マスタ -- 
CREATE TABLE m_err_extension
(
ERR_EXTENSION_NO			 INT NOT NULL
,ERR_EXTENSION			 VARCHAR(100) NOT NULL
,PRIMARY KEY(ERR_EXTENSION_NO));

