//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSF602.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSF602.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetKey, ResetApp will restart application!.
        /// </summary>
        public static string ABOUT_RESET_ALERT {
            get {
                return ResourceManager.GetString("ABOUT_RESET_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset App.
        /// </summary>
        public static string ABOUT_RESETAPP {
            get {
                return ResourceManager.GetString("ABOUT_RESETAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Key.
        /// </summary>
        public static string ABOUT_RESETKEY {
            get {
                return ResourceManager.GetString("ABOUT_RESETKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AKBlogo {
            get {
                object obj = ResourceManager.GetObject("AKBlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want changed the alarm value to all sensor ?.
        /// </summary>
        public static string ALARM_ALL_CONFIRM {
            get {
                return ResourceManager.GetString("ALARM_ALL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Report.
        /// </summary>
        public static string ALARM_TAB {
            get {
                return ResourceManager.GetString("ALARM_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Test.
        /// </summary>
        public static string ALARM_TEST {
            get {
                return ResourceManager.GetString("ALARM_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string APP_VERSION {
            get {
                return ResourceManager.GetString("APP_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close?.
        /// </summary>
        public static string APPCLOSE_CONFIRM_MSG {
            get {
                return ResourceManager.GetString("APPCLOSE_CONFIRM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string APPCLOSE_CONFIRM_MSG_TITLE {
            get {
                return ResourceManager.GetString("APPCLOSE_CONFIRM_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string BLOCK_LINE {
            get {
                return ResourceManager.GetString("BLOCK_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string BLOCK_PRODUCT {
            get {
                return ResourceManager.GetString("BLOCK_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sensors.
        /// </summary>
        public static string BLOCK_SENSORS {
            get {
                return ResourceManager.GetString("BLOCK_SENSORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string BLOCK_STATUS {
            get {
                return ResourceManager.GetString("BLOCK_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete this record?.
        /// </summary>
        public static string COMFIRM_MSG_DELETE {
            get {
                return ResourceManager.GetString("COMFIRM_MSG_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CUSTOMER {
            get {
                return ResourceManager.GetString("CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string DAY_FRI {
            get {
                return ResourceManager.GetString("DAY_FRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string DAY_MON {
            get {
                return ResourceManager.GetString("DAY_MON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string DAY_SAT {
            get {
                return ResourceManager.GetString("DAY_SAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string DAY_SUN {
            get {
                return ResourceManager.GetString("DAY_SUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string DAY_THU {
            get {
                return ResourceManager.GetString("DAY_THU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string DAY_TUE {
            get {
                return ResourceManager.GetString("DAY_TUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string DAY_WED {
            get {
                return ResourceManager.GetString("DAY_WED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string DEVICE_BTN_CLEAR {
            get {
                return ResourceManager.GetString("DEVICE_BTN_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Default.
        /// </summary>
        public static string DEVICE_BTN_RESETDEFAULT {
            get {
                return ResourceManager.GetString("DEVICE_BTN_RESETDEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DEVICE_BTN_SAVE {
            get {
                return ResourceManager.GetString("DEVICE_BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DEVICE_BTN_SAVESETTING {
            get {
                return ResourceManager.GetString("DEVICE_BTN_SAVESETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string DEVICE_CBO_ACTIVE {
            get {
                return ResourceManager.GetString("DEVICE_CBO_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive.
        /// </summary>
        public static string DEVICE_CBO_DEACTIVE {
            get {
                return ResourceManager.GetString("DEVICE_CBO_DEACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string DEVICE_COL_ACTIVE {
            get {
                return ResourceManager.GetString("DEVICE_COL_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Value.
        /// </summary>
        public static string DEVICE_COL_ALARMVALUE {
            get {
                return ResourceManager.GetString("DEVICE_COL_ALARMVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        public static string DEVICE_COL_SENSORNAME {
            get {
                return ResourceManager.GetString("DEVICE_COL_SENSORNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change device settings?.
        /// </summary>
        public static string DEVICE_CONFIRM_MSG {
            get {
                return ResourceManager.GetString("DEVICE_CONFIRM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DEVICE_CONFIRM_MSG_TITLE {
            get {
                return ResourceManager.GetString("DEVICE_CONFIRM_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Setting.
        /// </summary>
        public static string DEVICE_GRP_BLOCKSETTING {
            get {
                return ResourceManager.GetString("DEVICE_GRP_BLOCKSETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string DEVICE_LBL_ACTIVE {
            get {
                return ResourceManager.GetString("DEVICE_LBL_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string DEVICE_LBL_ACTIVESENSOR {
            get {
                return ResourceManager.GetString("DEVICE_LBL_ACTIVESENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Value.
        /// </summary>
        public static string DEVICE_LBL_ALARMVALUE {
            get {
                return ResourceManager.GetString("DEVICE_LBL_ALARMVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Name.
        /// </summary>
        public static string DEVICE_LBL_BLOCKNAME {
            get {
                return ResourceManager.GetString("DEVICE_LBL_BLOCKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List sensor of block.
        /// </summary>
        public static string DEVICE_LBL_HEADERTEXT {
            get {
                return ResourceManager.GetString("DEVICE_LBL_HEADERTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string DEVICE_LBL_IPADDRESS {
            get {
                return ResourceManager.GetString("DEVICE_LBL_IPADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal Display.
        /// </summary>
        public static string DEVICE_LBL_ORDINALDISPLAY {
            get {
                return ResourceManager.GetString("DEVICE_LBL_ORDINALDISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string DEVICE_LBL_PORT {
            get {
                return ResourceManager.GetString("DEVICE_LBL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Name.
        /// </summary>
        public static string DEVICE_LBL_SENSORNAME {
            get {
                return ResourceManager.GetString("DEVICE_LBL_SENSORNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Setting.
        /// </summary>
        public static string DEVICE_LBL_SENSORSETTING {
            get {
                return ResourceManager.GetString("DEVICE_LBL_SENSORSETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the block: {0} - {1}.
        /// </summary>
        public static string ERROR_MESSAGE_CONTENT_1 {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE_CONTENT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data: {0} - {1}.
        /// </summary>
        public static string ERROR_MESSAGE_CONTENT_2 {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE_CONTENT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message:.
        /// </summary>
        public static string ERROR_MESSAGE_HEADER {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message Manager.
        /// </summary>
        public static string ERROR_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input {0} password.
        /// </summary>
        public static string FOMAT_MSG_BLANK {
            get {
                return ResourceManager.GetString("FOMAT_MSG_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input {0}.
        /// </summary>
        public static string FOMAT_MSG_BLANK_USER {
            get {
                return ResourceManager.GetString("FOMAT_MSG_BLANK_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block name cannot be more than 8 characters.
        /// </summary>
        public static string FOMAT_MSG_BLOCKNAME_VALIDATE {
            get {
                return ResourceManager.GetString("FOMAT_MSG_BLOCKNAME_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block name already exists.
        /// </summary>
        public static string FOMAT_MSG_EXIST_BLOCKNAME {
            get {
                return ResourceManager.GetString("FOMAT_MSG_EXIST_BLOCKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor name already exists.
        /// </summary>
        public static string FOMAT_MSG_EXIST_SENSORNAME {
            get {
                return ResourceManager.GetString("FOMAT_MSG_EXIST_SENSORNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists.
        /// </summary>
        public static string FOMAT_MSG_EXIST_USER {
            get {
                return ResourceManager.GetString("FOMAT_MSG_EXIST_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input {0} is a number than 0.
        /// </summary>
        public static string FOMAT_MSG_INPUT_NUMBER {
            get {
                return ResourceManager.GetString("FOMAT_MSG_INPUT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GraphType1 {
            get {
                object obj = ResourceManager.GetObject("GraphType1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GraphType2 {
            get {
                object obj = ResourceManager.GetObject("GraphType2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GraphType3 {
            get {
                object obj = ResourceManager.GetObject("GraphType3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon language {
            get {
                object obj = ResourceManager.GetObject("language", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        public static string LANGUAGE_BTN_AGREE {
            get {
                return ResourceManager.GetString("LANGUAGE_BTN_AGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LANGUAGE_BTN_CANCEL {
            get {
                return ResourceManager.GetString("LANGUAGE_BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select display language:.
        /// </summary>
        public static string LANGUAGE_HEADER {
            get {
                return ResourceManager.GetString("LANGUAGE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE_TITLE {
            get {
                return ResourceManager.GetString("LANGUAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string LICENSE_BTN_ACTIVE {
            get {
                return ResourceManager.GetString("LICENSE_BTN_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File.
        /// </summary>
        public static string LICENSE_BTN_LOAD_FILE {
            get {
                return ResourceManager.GetString("LICENSE_BTN_LOAD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Machine is not activated!.
        /// </summary>
        public static string LICENSE_LBL_CONTENT1 {
            get {
                return ResourceManager.GetString("LICENSE_LBL_CONTENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send the Machine Code  to System Admin!.
        /// </summary>
        public static string LICENSE_LBL_CONTENT2 {
            get {
                return ResourceManager.GetString("LICENSE_LBL_CONTENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string LICENSE_LBL_KEY {
            get {
                return ResourceManager.GetString("LICENSE_LBL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Code.
        /// </summary>
        public static string LICENSE_LBL_MACHINECODE {
            get {
                return ResourceManager.GetString("LICENSE_LBL_MACHINECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATIRON DSF602 Control Software.
        /// </summary>
        public static string LICENSE_TITLE {
            get {
                return ResourceManager.GetString("LICENSE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon line_chart {
            get {
                object obj = ResourceManager.GetObject("line_chart", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string LOGIN_BTN_EXIT {
            get {
                return ResourceManager.GetString("LOGIN_BTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN_BTN_LOGIN {
            get {
                return ResourceManager.GetString("LOGIN_BTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LOGIN_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string LOGIN_USERNAME {
            get {
                return ResourceManager.GetString("LOGIN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo_systech3 {
            get {
                object obj = ResourceManager.GetObject("logo_systech3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logoSSD {
            get {
                object obj = ResourceManager.GetObject("logoSSD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string MAIN_BTN_DATA {
            get {
                return ResourceManager.GetString("MAIN_BTN_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string MAIN_BTN_DEVICE {
            get {
                return ResourceManager.GetString("MAIN_BTN_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MAIN_BTN_LANGUAGE {
            get {
                return ResourceManager.GetString("MAIN_BTN_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string MAIN_BTN_RESET {
            get {
                return ResourceManager.GetString("MAIN_BTN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string MAIN_BTN_UPDATE {
            get {
                return ResourceManager.GetString("MAIN_BTN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string MAIN_BTN_USER {
            get {
                return ResourceManager.GetString("MAIN_BTN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION.
        /// </summary>
        public static string MAIN_LOCATION {
            get {
                return ResourceManager.GetString("MAIN_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string MAIN_TAB_ERR {
            get {
                return ResourceManager.GetString("MAIN_TAB_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAPH.
        /// </summary>
        public static string MAIN_TAB_GRAPH {
            get {
                return ResourceManager.GetString("MAIN_TAB_GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        public static string MAIN_TAB_MAP {
            get {
                return ResourceManager.GetString("MAIN_TAB_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSF602 Software Monitor.
        /// </summary>
        public static string MAIN_TITLE {
            get {
                return ResourceManager.GetString("MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        public static string MAIN_VIEW {
            get {
                return ResourceManager.GetString("MAIN_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location (Block).
        /// </summary>
        public static string MAP_HEADER {
            get {
                return ResourceManager.GetString("MAP_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string MEASURE_BTN_EXCEL {
            get {
                return ResourceManager.GetString("MEASURE_BTN_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string MEASURE_BTN_FILTER {
            get {
                return ResourceManager.GetString("MEASURE_BTN_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MEASURE_BTN_SEARCH {
            get {
                return ResourceManager.GetString("MEASURE_BTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Value.
        /// </summary>
        public static string MEASURE_COL_ALARMVALUE {
            get {
                return ResourceManager.GetString("MEASURE_COL_ALARMVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Name.
        /// </summary>
        public static string MEASURE_COL_BLOCKNAME {
            get {
                return ResourceManager.GetString("MEASURE_COL_BLOCKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MEASURE_COL_DELETE {
            get {
                return ResourceManager.GetString("MEASURE_COL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string MEASURE_COL_ENDTIME {
            get {
                return ResourceManager.GetString("MEASURE_COL_ENDTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string MEASURE_COL_RESULT {
            get {
                return ResourceManager.GetString("MEASURE_COL_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string MEASURE_COL_RESULTDETAIL {
            get {
                return ResourceManager.GetString("MEASURE_COL_RESULTDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Name.
        /// </summary>
        public static string MEASURE_COL_SENSORNAME {
            get {
                return ResourceManager.GetString("MEASURE_COL_SENSORNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string MEASURE_COL_STARTTIME {
            get {
                return ResourceManager.GetString("MEASURE_COL_STARTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string MEASURE_COL_TIMEDETAIL {
            get {
                return ResourceManager.GetString("MEASURE_COL_TIMEDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string MEASURE_COL_USER {
            get {
                return ResourceManager.GetString("MEASURE_COL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value (V).
        /// </summary>
        public static string MEASURE_COL_VALUEDETAIL {
            get {
                return ResourceManager.GetString("MEASURE_COL_VALUEDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string MEASURE_LBL_BLOCK {
            get {
                return ResourceManager.GetString("MEASURE_LBL_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MEASURE_LBL_DATE {
            get {
                return ResourceManager.GetString("MEASURE_LBL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string MEASURE_LBL_RESULT {
            get {
                return ResourceManager.GetString("MEASURE_LBL_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        public static string MEASURE_LBL_SENSOR {
            get {
                return ResourceManager.GetString("MEASURE_LBL_SENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show the voltage exceeds the threshold.
        /// </summary>
        public static string MEASURE_LBL_TEXT {
            get {
                return ResourceManager.GetString("MEASURE_LBL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string MEASURE_LBL_TIME {
            get {
                return ResourceManager.GetString("MEASURE_LBL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MEASURE_LBL_TYPE {
            get {
                return ResourceManager.GetString("MEASURE_LBL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MEASURE_LBL_USERS {
            get {
                return ResourceManager.GetString("MEASURE_LBL_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay &amp; IB.
        /// </summary>
        public static string MEASURE_MODE_DECAY {
            get {
                return ResourceManager.GetString("MEASURE_MODE_DECAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IB.
        /// </summary>
        public static string MEASURE_MODE_ION {
            get {
                return ResourceManager.GetString("MEASURE_MODE_ION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volt.
        /// </summary>
        public static string MEASURE_MODE_VOLT {
            get {
                return ResourceManager.GetString("MEASURE_MODE_VOLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string MEASURE_RESULT_FAIL {
            get {
                return ResourceManager.GetString("MEASURE_RESULT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string MEASURE_RESULT_PASS {
            get {
                return ResourceManager.GetString("MEASURE_RESULT_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurment Management.
        /// </summary>
        public static string MEASURE_TITLE {
            get {
                return ResourceManager.GetString("MEASURE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Type.
        /// </summary>
        public static string MEASURE_TYPE {
            get {
                return ResourceManager.GetString("MEASURE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate machine fail! Please contact system Admin!.
        /// </summary>
        public static string MSG_ACTIVATE_ERR {
            get {
                return ResourceManager.GetString("MSG_ACTIVATE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password fail.
        /// </summary>
        public static string MSG_CHANGE_PASS_ERR {
            get {
                return ResourceManager.GetString("MSG_CHANGE_PASS_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password success.
        /// </summary>
        public static string MSG_CHANGE_PASS_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_CHANGE_PASS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete user?.
        /// </summary>
        public static string MSG_COMFIRM_DELETE {
            get {
                return ResourceManager.GetString("MSG_COMFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want open file report?.
        /// </summary>
        public static string MSG_COMFIRM_EXCEL {
            get {
                return ResourceManager.GetString("MSG_COMFIRM_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset device current?.
        /// </summary>
        public static string MSG_COMFIRM_RESET {
            get {
                return ResourceManager.GetString("MSG_COMFIRM_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string MSG_ERR_CURRENT {
            get {
                return ResourceManager.GetString("MSG_ERR_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export excel errors..
        /// </summary>
        public static string MSG_ERR_EXCEL {
            get {
                return ResourceManager.GetString("MSG_ERR_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered incorrect username or password!.
        /// </summary>
        public static string MSG_ERR_LOGIN {
            get {
                return ResourceManager.GetString("MSG_ERR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string MSG_ERR_NEW {
            get {
                return ResourceManager.GetString("MSG_ERR_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input password..
        /// </summary>
        public static string MSG_ERR_PASS_BLANK {
            get {
                return ResourceManager.GetString("MSG_ERR_PASS_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has erros in process..
        /// </summary>
        public static string MSG_ERR_PROCESS {
            get {
                return ResourceManager.GetString("MSG_ERR_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to re-type new.
        /// </summary>
        public static string MSG_ERR_RETYPENEW {
            get {
                return ResourceManager.GetString("MSG_ERR_RETYPENEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input username..
        /// </summary>
        public static string MSG_ERR_USER_BLANK {
            get {
                return ResourceManager.GetString("MSG_ERR_USER_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the connection again..
        /// </summary>
        public static string MSG_ERROR_CHECKCONNECTION {
            get {
                return ResourceManager.GetString("MSG_ERROR_CHECKCONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MSG_ERROR_TITLE {
            get {
                return ResourceManager.GetString("MSG_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input key active!.
        /// </summary>
        public static string MSG_KEY_BLANLK {
            get {
                return ResourceManager.GetString("MSG_KEY_BLANLK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} to {2}.
        /// </summary>
        public static string MSG_OUTOF_RANGE {
            get {
                return ResourceManager.GetString("MSG_OUTOF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match the confirm password.
        /// </summary>
        public static string MSG_PASS_NOT_SAME {
            get {
                return ResourceManager.GetString("MSG_PASS_NOT_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset setting fail.
        /// </summary>
        public static string MSG_RESET_SETTING_ERR {
            get {
                return ResourceManager.GetString("MSG_RESET_SETTING_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save setting fail.
        /// </summary>
        public static string MSG_SAVE_SETTING_ERR {
            get {
                return ResourceManager.GetString("MSG_SAVE_SETTING_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save setting success.
        /// </summary>
        public static string MSG_SAVE_SETTING_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SAVE_SETTING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string MSG_SETTING {
            get {
                return ResourceManager.GetString("MSG_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update error.
        /// </summary>
        public static string MSG_UPDATE_ERR {
            get {
                return ResourceManager.GetString("MSG_UPDATE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found..
        /// </summary>
        public static string MSG_WAR_DATA {
            get {
                return ResourceManager.GetString("MSG_WAR_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 1 row data to export excel..
        /// </summary>
        public static string MSG_WAR_EXCEL {
            get {
                return ResourceManager.GetString("MSG_WAR_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel template not found..
        /// </summary>
        public static string MSG_WAR_EXCELTEMPLATE {
            get {
                return ResourceManager.GetString("MSG_WAR_EXCELTEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN;
        ///CREATE TABLE IF NOT EXISTS MUser (UserId INTEGER PRIMARY KEY AUTOINCREMENT, UserName TEXT, Password TEXT,FullName TEXT,Email TEXT, UpdateTime DATETIME,Role INTEGER);
        ///CREATE TABLE IF NOT EXISTS Block (BlockId INTEGER PRIMARY KEY AUTOINCREMENT, BlockName TEXT, Ip_Address TEXT,Port INTEGER,Active INTEGER, DefaultParams TEXT, UpdateTime DATETIME,UpdateBy INTEGER);
        ///CREATE TABLE IF NOT EXISTS Sensors (SensorId INTEGER PRIMARY KEY AUTOINCREMENT, SensorName TEXT, Alarm_Value INTEGER, Ordinal_Display INTER [rest of string was truncated]&quot;;.
        /// </summary>
        public static string queryfist {
            get {
                return ResourceManager.GetString("queryfist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        public static string RESTORE_BTN_AGREE {
            get {
                return ResourceManager.GetString("RESTORE_BTN_AGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RESTORE_BTN_CLOSE {
            get {
                return ResourceManager.GetString("RESTORE_BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select version:.
        /// </summary>
        public static string RESTORE_LBL_HEADER {
            get {
                return ResourceManager.GetString("RESTORE_LBL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Version.
        /// </summary>
        public static string RESTOREVERSION_TITLE {
            get {
                return ResourceManager.GetString("RESTOREVERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string SELECT_ALL_SHOW {
            get {
                return ResourceManager.GetString("SELECT_ALL_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm!.
        /// </summary>
        public static string SENSOR_ALARM {
            get {
                return ResourceManager.GetString("SENSOR_ALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No use.
        /// </summary>
        public static string SENSOR_NOUSE {
            get {
                return ResourceManager.GetString("SENSOR_NOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string SENSOR_RUNNING {
            get {
                return ResourceManager.GetString("SENSOR_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string SOFTWARE {
            get {
                return ResourceManager.GetString("SOFTWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time format is incorrect.
        /// </summary>
        public static string TIME_INCORRECT_FORMAT {
            get {
                return ResourceManager.GetString("TIME_INCORRECT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Time.
        /// </summary>
        public static string TITLE_DECAY {
            get {
                return ResourceManager.GetString("TITLE_DECAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Measure Time.
        /// </summary>
        public static string TITLE_DECAY_AUTO {
            get {
                return ResourceManager.GetString("TITLE_DECAY_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure count.
        /// </summary>
        public static string TITLE_DECAY_COL_COUNT {
            get {
                return ResourceManager.GetString("TITLE_DECAY_COL_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop IB Measure.
        /// </summary>
        public static string TITLE_DECAY_IBSTOPTIME {
            get {
                return ResourceManager.GetString("TITLE_DECAY_IBSTOPTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Peak Voltage.
        /// </summary>
        public static string TITLE_DECAY_IBVAL {
            get {
                return ResourceManager.GetString("TITLE_DECAY_IBVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay To.
        /// </summary>
        public static string TITLE_DECAY_LOWVAL {
            get {
                return ResourceManager.GetString("TITLE_DECAY_LOWVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Decay.
        /// </summary>
        public static string TITLE_DECAY_STOPTIME {
            get {
                return ResourceManager.GetString("TITLE_DECAY_STOPTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Alarm.
        /// </summary>
        public static string TITLE_DECAY_TIME {
            get {
                return ResourceManager.GetString("TITLE_DECAY_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging.
        /// </summary>
        public static string TITLE_DECAY_UPVAL {
            get {
                return ResourceManager.GetString("TITLE_DECAY_UPVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default values.
        /// </summary>
        public static string TITLE_DEFAULT_VALUES {
            get {
                return ResourceManager.GetString("TITLE_DEFAULT_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Balance.
        /// </summary>
        public static string TITLE_IB {
            get {
                return ResourceManager.GetString("TITLE_IB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string TITLE_VOLT {
            get {
                return ResourceManager.GetString("TITLE_VOLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckVersion.
        /// </summary>
        public static string UPDATE_BTN_CHECK {
            get {
                return ResourceManager.GetString("UPDATE_BTN_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UPDATE_BTN_CLOSE {
            get {
                return ResourceManager.GetString("UPDATE_BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string UPDATE_BTN_RESTORE {
            get {
                return ResourceManager.GetString("UPDATE_BTN_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UPDATE_BTN_UPLOAD {
            get {
                return ResourceManager.GetString("UPDATE_BTN_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check update and restore.
        /// </summary>
        public static string UPDATE_CHECK_CONTENT {
            get {
                return ResourceManager.GetString("UPDATE_CHECK_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version is {0} !.
        /// </summary>
        public static string UPDATE_CHECK_INFO {
            get {
                return ResourceManager.GetString("UPDATE_CHECK_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string UPDATE_DOWNLOADED_TEXT {
            get {
                return ResourceManager.GetString("UPDATE_DOWNLOADED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is availble.
        /// </summary>
        public static string UPDATE_LBL_CONTENT {
            get {
                return ResourceManager.GetString("UPDATE_LBL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        public static string UPDATE_LBL_CONTENT_DOWNLOADED {
            get {
                return ResourceManager.GetString("UPDATE_LBL_CONTENT_DOWNLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App is up to date.
        /// </summary>
        public static string UPDATE_LBL_CONTENT_NOVERSION {
            get {
                return ResourceManager.GetString("UPDATE_LBL_CONTENT_NOVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSF602 {0} is now available (you have {1}). Would you like to download the new version now?.
        /// </summary>
        public static string UPDATE_LBL_INFO {
            get {
                return ResourceManager.GetString("UPDATE_LBL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Starting....
        /// </summary>
        public static string UPDATE_LBL_INFO_DOWNLOAD {
            get {
                return ResourceManager.GetString("UPDATE_LBL_INFO_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already the latest version, there are no new updates available at this moment.
        /// </summary>
        public static string UPDATE_LBL_INFO_NOVERSION {
            get {
                return ResourceManager.GetString("UPDATE_LBL_INFO_NOVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string UPDATE_LBL_PROGRESS {
            get {
                return ResourceManager.GetString("UPDATE_LBL_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the program is processing....
        /// </summary>
        public static string UPDATE_MESSAGE_SENDER {
            get {
                return ResourceManager.GetString("UPDATE_MESSAGE_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart and update the application.
        /// </summary>
        public static string UPDATE_MESSAGEBOX_MSG {
            get {
                return ResourceManager.GetString("UPDATE_MESSAGEBOX_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UPDATE_TITLE_SENDER {
            get {
                return ResourceManager.GetString("UPDATE_TITLE_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Management.
        /// </summary>
        public static string UPDATEVERSION_TITLE {
            get {
                return ResourceManager.GetString("UPDATEVERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon user_list {
            get {
                object obj = ResourceManager.GetObject("user_list", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string USERS_BTN_CREATEUSER {
            get {
                return ResourceManager.GetString("USERS_BTN_CREATEUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Change.
        /// </summary>
        public static string USERS_BTN_SAVECHANGE {
            get {
                return ResourceManager.GetString("USERS_BTN_SAVECHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save User.
        /// </summary>
        public static string USERS_BTN_SAVEUSER {
            get {
                return ResourceManager.GetString("USERS_BTN_SAVEUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string USERS_CBOROLE_ADMIN {
            get {
                return ResourceManager.GetString("USERS_CBOROLE_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string USERS_CBOROLE_USER {
            get {
                return ResourceManager.GetString("USERS_CBOROLE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string USERS_COL_DELETE {
            get {
                return ResourceManager.GetString("USERS_COL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string USERS_COL_FULLNAME {
            get {
                return ResourceManager.GetString("USERS_COL_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string USERS_COL_ROLE {
            get {
                return ResourceManager.GetString("USERS_COL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string USERS_COL_USERNAME {
            get {
                return ResourceManager.GetString("USERS_COL_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string USERS_CURRENTPASS {
            get {
                return ResourceManager.GetString("USERS_CURRENTPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string USERS_EMAIL {
            get {
                return ResourceManager.GetString("USERS_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string USERS_FULLNAME {
            get {
                return ResourceManager.GetString("USERS_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string USERS_NEWPASS {
            get {
                return ResourceManager.GetString("USERS_NEWPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string USERS_PASSWORD {
            get {
                return ResourceManager.GetString("USERS_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type password.
        /// </summary>
        public static string USERS_RETYPEPASS {
            get {
                return ResourceManager.GetString("USERS_RETYPEPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string USERS_ROLE {
            get {
                return ResourceManager.GetString("USERS_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string USERS_TAB_CHANGEPASSWORD {
            get {
                return ResourceManager.GetString("USERS_TAB_CHANGEPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string USERS_TAB_USERS {
            get {
                return ResourceManager.GetString("USERS_TAB_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Users Management.
        /// </summary>
        public static string USERS_TITLE {
            get {
                return ResourceManager.GetString("USERS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string USERS_USERNAME {
            get {
                return ResourceManager.GetString("USERS_USERNAME", resourceCulture);
            }
        }
    }
}
