CREATE SEQUENCE announce_sequence AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE bulletin_board_sequence AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE query_sequence AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE incident_case_sequence AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE request_sequence AS INT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE information_sequence AS INT START WITH 1 INCREMENT BY 1;
